web:
  image: seqasim/brain_plot
  restart: always
  expose:
    - "5000"
  volumes:
    - .:/code
  working_dir: /code
  command: /usr/local/bin/gunicorn -w 4 -b 0.0.0.0:5000 main:app

nginx:
  image: nginx
  restart: always
  ports:
    - "80:80"
  volumes:
    - /www/static
  links:
    - web:web